#spring.datasource.url=jdbc:mysql://books-aws.c1aka0omejet.eu-north-1.rds.amazonaws.com:3306/db_books?useSSL=false&serverTimezone=UTC

##ANTIGUA CONEXION CON LOCALHOST
spring.datasource.url=jdbc:mysql://localhost:3306/db_books?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC  
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug

#server.port=5000
#spring.jpa.show-sql=true

#-----------------------------------------------------------------------------------------------------------------------------------

#SI NO AÑADES NINGUNA Y EN TU PROYECTO ESTA LA DEPENDECIA SPRING SECURITY CUANDO "INCICIALICES" EL PROYECTO, LA TERMINAL TE GENERA UNA CONTRASEÑA. (EL USUARIO POR DEFECTO ES ROOT O USER)
#SPRING SECURITY (PARA VER LA FUNCIONALIDAD DEL BACKEND CON CONTRASE�A EN POSTMAN SI QUIERES AÑADIR ALGUNA)
#spring.security.user.name=alfredo
#spring.security.user.password=alfredo123

#-----------------------------------------------------------------------------------------------------------------------------------

#SWAGGER CONFIGURATION (API DOCS)
#springdoc.swagger-ui.enabled=true
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html






